### ISSUE TITLE
Make it possible to set top_n in most_similar words

### ISSUE THREAD

**Issue by CateGitau** [dsfsi/textaugment#16]
Can you please make it possible to choose top_n most similar words instead of having to replace with random synonym from the default 10 synonyms.

**Comment by vukosim** [comment]
Did this get resolved @CateGitau ?

**Comment by CateGitau** [comment]
No, i don't think so.

**Comment by JosephSefara** [comment]
Can you @CateGitau check [this branch](https://github.com/AchatY/textaugment/tree/synonym/top_n) if the implementation is correct. If not please explain whats missing.

**Comment by CateGitau** [comment]
@JosephSefara This is okay but only on EDA, I guess the same should be done on Word2Vec and WordNet as well.
