### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by barseghyanartur** [dsfsi/textaugment#31]
Please, make a new release.

**Comment by vukosim** [comment]
@JosephSefara People have spoken. Lets do it.

**Comment by barseghyanartur** [comment]
@vukosim 

I just noticed there is a new https://github.com/dsfsi/textaugment/blob/master/textaugment/aeda.py augmenter. And there's also additional method `synonym_replacement_top_n` in the https://github.com/dsfsi/textaugment/blob/master/textaugment/eda.py augmenter. I want to use these (because they are extremely lightweight and fit my task perfectly). :)

**Comment by JosephSefara** [comment]
@barseghyanartur go ahead test the latest release

**Comment by barseghyanartur** [comment]
@JosephSefara 

It works great. Thanks!
