### ISSUE TITLE
UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by ShrikanthSingh** [dsfsi/textaugment#9]
The code snippet I used :
```
from textaugment import Word2vec
t = Word2vec(model='/content/drive/My Drive/ewiki8/enwik9')
#t.augment('The stories are good')
```

**Comment by SefaraTJ** [comment]
The problem might be how you saved your model. [See](https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key). Try building the model in the same notebook and test.

**Comment by ShrikanthSingh** [comment]
> The problem might be how you saved your model. [See](https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key). Try building the model in the same notebook and test.

I tried even loading the ' Google News from Google drive' but it throws error `UnpicklingError: invalid load key, '3'`.

**Comment by SefaraTJ** [comment]
Model not trained using Gensim you have to load it using this [code](https://gist.github.com/bhaettasch/d7f4e22e79df3c8b6c20) then pass that model:
E.g
```python
from gensim.models import Word2Vec
model = Word2Vec.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True, norm_only=True)
from textaugment import Word2vec
t = Word2vec(model=model)
```
